spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acatlan
    username: secretario
    password: secretario
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: flPWbpgpWrPFiaLkY7sJfS9pK83LWiqz
  expiration: PT24H